### ISSUE TITLE
Tests fail on OSX

### ISSUE THREAD

**Issue by Mossop** [Backblaze/b2-sdk-python#119]
Running tests on a clean checkout on OSX fail:

```
running nosetests
running egg_info
writing b2sdk.egg-info/PKG-INFO
writing dependency_links to b2sdk.egg-info/dependency_links.txt
writing requirements to b2sdk.egg-info/requires.txt
writing top-level names to b2sdk.egg-info/top_level.txt
reading manifest file 'b2sdk.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'b2sdk.egg-info/SOURCES.txt'
/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/config.py:430: DeprecationWarning: Use of multiple -w arguments is deprecated and support may be removed in a future release. You can get the same behavior by passing directories without the -w argument on the command line, or by using the --tests argument in a configuration file.
  warn("Use of multiple -w arguments is deprecated and "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/dave/workspace/b2-sdk-python/setup.py", line 52, in <module>
    setup(
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/commands.py", line 158, in run
    TestProgram(argv=argv, config=self.__config)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/multiprocess.py", line 239, in configure
    _import_mp()
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/multiprocess.py", line 150, in _import_mp
    m = Manager()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    setup(
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/commands.py", line 158, in run
    TestProgram(argv=argv, config=self.__config)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/multiprocess.py", line 239, in configure
    _import_mp()
  File "/Users/dave/config/repos/pyenv/versions/b2-sdk/lib/python3.8/site-packages/nose/plugins/multiprocess.py", line 150, in _import_mp
    m = Manager()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/dave/config/repos/pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
make: *** [test] Error 1
```

**Comment by mlech-reef** [comment]
The CI is running all test suites on OSX system without any problem. Is this problem still exist?
