### ISSUE TITLE
Python 3.10 Compatible 

### ISSUE THREAD

**Issue by linnit** [Backblaze/b2-sdk-python#288]
I understand 3.10 has just been released, but it will get raised at some point.

At the moment the following happens when testing with Python 3.10.0

```
Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from b2sdk.v2 import InMemoryAccountInfo
>>> 
>>> info = InMemoryAccountInfo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/.env/env/lib64/python3.10/site-packages/b2sdk/account_info/in_memory.py", line 42, in __init__
    super(InMemoryAccountInfo, self).__init__(*args, **kwargs)
  File "/home/ryan/.env/env/lib64/python3.10/site-packages/b2sdk/account_info/upload_url_pool.py", line 83, in __init__
    self._reset_upload_pools()
  File "/home/ryan/.env/env/lib64/python3.10/site-packages/b2sdk/account_info/upload_url_pool.py", line 91, in _reset_upload_pools
    self._bucket_uploads = self.BUCKET_UPLOAD_POOL_CLASS()
  File "/home/ryan/.env/env/lib64/python3.10/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
TypeError: UploadUrlPool.__init__() takes 1 positional argument but 2 were given
>>> 
```

**Comment by linnit** [comment]
@ppolewicz appreciate the response, I initially starting using `InMemoryAccountInfo` as that is mentioned in [this tutorial](https://b2-sdk-python.readthedocs.io/en/master/tutorial.html). It's only when you look deeper into the documentation regarding the different AccountInfo implementations, does it advise that using `InMemoryAccountInfo` is discouraged.

I'm using b2-sdk-python in a tool that converts videos to a "web" format and uploads them to a b2 bucket, still early in development at the moment though and I've only been using b2-sdk-python for a couple of weeks, so not a huge amount of experience with the library. The reasoning for then using `InMemoryAccountInfo`, although slower than `SqliteAccountInfo`, I am only uploading large files infrequently, so don't think I will be affected by the performance impact or having to retrieve an authorization token every time.

In regards to the "weird import structure of this project", as I've only recently started using b2-sdk-python, I can't say I've delved too much into the structure so couldn't comment too much on it, sorry.
