### ISSUE TITLE
[BUG] ValueError thrown when uploading local file with sub-millisecond mod time

### ISSUE THREAD

**Issue by ChangeinX** [Backblaze/b2-sdk-python#368]
**Environment**
Tester: ChangeinX
Version: b2sdk==1.18.0

**Expected Result**

What was wanted:

Upload a local file to the Backblaze bucket while preserving last modified time

**Actual Result**

What happened:

```
Traceback (most recent call last):
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\lab\lambda_handler.py", line 54, in <module>
    main()
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\lab\lambda_handler.py", line 50, in main
    upload_file(args.file_path)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\lab\lambda_handler.py", line 36, in upload_file
    bucket.upload_local_file(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\logfury\_logfury\trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\bucket.py", line 505, in upload_local_file
    return self.upload(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\logfury\_logfury\trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\bucket.py", line 551, in upload
    return self.create_file(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\logfury\_logfury\trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\bucket.py", line 605, in create_file
    return self._create_file(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\bucket.py", line 699, in _create_file
    return emerger_method(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\logfury\_logfury\trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\transfer\emerge\emerger.py", line 82, in emerge
    return self.emerge_executor.execute_emerge_plan(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\transfer\emerge\executor.py", line 71, in execute_emerge_plan
    return execution.execute_plan(emerge_plan)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\transfer\emerge\executor.py", line 112, in execute_plan
    return future.result()
  File "C:\Users\ChangeinX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\ChangeinX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\ChangeinX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\transfer\outbound\upload_manager.py", line 219, in _upload_small_file
    return self.services.api.file_version_factory.from_api_response(response)
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\file_version.py", line 497, in from_api_response
    return self.FILE_VERSION_CLASS(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\file_version.py", line 248, in __init__
    super().__init__(
  File "C:\Users\ChangeinX\PycharmProjects\PJDB\venv\lib\site-packages\b2sdk\file_version.py", line 89, in __init__
    self.mod_time_millis = int(self.file_info[SRC_LAST_MODIFIED_MILLIS])
ValueError: invalid literal for int() with base 10: '1671500543.5804098'
```

**Steps to Reproduce**
upload_file_to_backblaze.py

```
"""
This module will upload a file to backblaze b2.
"""

import argparse
import logging
import os

from b2sdk.v2 import B2Api as b2
from b2sdk.v2 import InMemoryAccountInfo

logger = logging.getLogger()
logger.setLevel(logging.INFO)

info = InMemoryAccountInfo()

b2_api = b2(info)
app_keyId = "<app_keyId>"
b2_appKey = "<b2_appKey>"
b2_api.authorize_account("production", app_keyId, b2_appKey)

bucket_name = "<bucket_name>"


def upload_file(file_path: str) -> None:
    """
    Upload a file to a backblaze bucket.
    :param file_path: The path to the file to upload.
    """
    logger.info(f'Uploading file: {file_path} to bucket: {bucket_name}')

    # Get the bucket to upload the file to
    bucket = b2_api.get_bucket_by_name(bucket_name)

    # Upload the file
    bucket.upload_local_file(
        local_file=file_path,
        file_name=os.path.basename(file_path),
        file_infos={'src_last_modified_millis': str(os.path.getmtime(file_path))},
    )

    logger.info(f'Finished uploading file: {file_path} to bucket: {bucket_name}')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--file_path', help='Path to the file to upload to backblaze')
    args = parser.parse_args()

    upload_file(args.file_path)


if __name__ == '__main__':
    main()
```

**Problem Description**

When specifying `'src_last_modified_millis'` no validation was performed on the input. This caused an Exception to be thrown.

**Behavior Affected**

The file uploads successfully, but an error is thrown after the upload has been processed.

**Comment by ppolewicz** [comment]
This was operator error, using float of seconds from epoch instead of int of milliseconds from epoch
