### ISSUE TITLE
ERROR:b2sdk.bucket:error when uploading

### ISSUE THREAD

**Issue by spinitron** [Backblaze/b2-sdk-python#72]
The command run from a cron.hourly script was

    b2 sync --noProgress --keepDays 14 /home/data/v2 b2://bhs-backup/ > /dev/null

b2 wrote to stderr

```
ERROR:b2sdk.bucket:error when uploading, upload_url was https://pod-000-1009-12.backblaze.com/b2api/v2/b2_upload_file/redacted/redacted
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/bucket.py", line 615, in _upload_small_file 
content_type, HEX_DIGITS_AT_END, file_info, hashing_stream 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/raw_api.py", line 533, in upload_file 
return self.b2_http.post_content_return_json(upload_url, headers, data_stream) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 297, in post_content_return_json 
response = _translate_and_retry(do_post, try_count, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 127, in _translate_and_retry 
return _translate_errors(fcn, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 60, in _translate_errors 
int(error['status']), error['code'], error['message'], post_params 
ServiceError: 500 internal_error incident id 62096cb3b343-0424780b144c
```

**Comment by spinitron** [comment]
This error was logged once on Sep 24

**Comment by ppolewicz** [comment]
This indicates a temporary server-side error encountered in b2-cli. The CLI tried to recover from the error automatically, but those attempts failed too. Further discussion about this is moved to #73.
