### ISSUE TITLE
B2ConnectionError. Max retries exceeded. Caused by NewConnectionError. Failed to establish a new connection

### ISSUE THREAD

**Issue by spinitron** [Backblaze/b2-sdk-python#75]
The command run from a cron.hourly script was

    b2 sync --noProgress --keepDays 14 /home/data/v2 b2://bhs-backup/ > /dev/null

b2 wrote to stderr

```
ERROR:b2sdk.bucket:error when uploading, upload_url was https://pod-000-1117-16.backblaze.com/b2api/v2/b2_upload_file/xxxx/xxxx
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/bucket.py", line 615, in _upload_small_file 
content_type, HEX_DIGITS_AT_END, file_info, hashing_stream 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/raw_api.py", line 533, in upload_file 
return self.b2_http.post_content_return_json(upload_url, headers, data_stream) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 297, in post_content_return_json 
response = _translate_and_retry(do_post, try_count, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 127, in _translate_and_retry 
return _translate_errors(fcn, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 84, in _translate_errors 
raise B2ConnectionError(str(e0)) 
B2ConnectionError: Connection error: HTTPSConnectionPool(host='pod-000-1117-16.backblaze.com', port=443): Max retries exceeded with url: /b2api/v2/b2_upload_file/xxxx/xxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f139ca04c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by spinitron** [comment]
This error was logged 7 times between Sep 7 and Sep 21

**Comment by ppolewicz** [comment]
This indicates a temporary server-side error encountered in b2-cli. The CLI tried to recover from the error automatically, but those attempts failed too. Further discussion about this is moved to #73.
