### ISSUE TITLE
400 bad_request more than one upload using auth token

### ISSUE THREAD

**Issue by fred-aero** [Backblaze/b2-sdk-python#79]
I have a loop uploading files locally to B2 cloud. After a few thousand uploads over a few hours, I get this error:
`b2sdk.exception.UnknownError: Unknown error: 400 bad_request more than one upload using auth token 4_0021a87abca5e6b0000000005_018fe4f8_97f3ec_uplg_wANv-9n9ent4nLDoDI0yMFmZqeQ=`

I feel like upload_local_file method should be able to handle renegotiating a new auth token on its own rather than failing as such.

**Comment by ppolewicz** [comment]
upload_local_file does renegotiate an auth token if one expires. This is different.

First of all, usually it is better to `sync` to upload multiple files, than loop and `upload_local_file`, you should look into it. Nevertheless, a bug of some sort was observed and I am not sure what to think of it. Perhaps an upload request has failed/timed out, but was still alive on the server and we reused an **upload token** (not an **auth token**, as misleadingly hinted by the server) to upload another file? @bwbeach can you shed some light on why the server forbids uploading multiple files with one **auth token**?

**Comment by ppolewicz** [comment]
The bug is here: https://github.com/Backblaze/b2-sdk-python/blob/ec0de1cc783a1f5caf8b4989b53eb7e1b7a7e766/b2sdk/bucket.py#L702

**Comment by ppolewicz** [comment]
@fred-aero please install a development version from https://github.com/Backblaze/b2-sdk-python/archive/fix_79.zip (https://github.com/Backblaze/b2-sdk-python/tree/fix_79) with `python setup.py install` and let me know if it fixes the problem.

**Comment by fred-aero** [comment]
I will for sure give it a shot, thanks!

**Comment by ppolewicz** [comment]
@fred-aero if you could confirm that it works as intended, I'd like to ship that fix before working on some other larger changes in the same area of code. Could you test it soon?

**Comment by fred-aero** [comment]
Sorry for the delay, I just set up two servers to perform a similar job to what gave me the error before. One server is using the posted fix while the other is acting as a control. I'm going to have them both run for a while and let you know what happens.

**Comment by fred-aero** [comment]
The server running fix_79 encountered the same error unfortunately.
Here is the full stack trace:
```
Traceback (most recent call last):
  File "b2_stress_test.py", line 106, in <module>
    main()
  File "b2_stress_test.py", line 91, in main
    b2_upload(bucket_recv, local_name, object_name)
  File "b2_stress_test.py", line 49, in b2_upload
    file_name=object_name
  File "/usr/local/lib/python3.7/dist-packages/logfury-0.1.2-py3.7.egg/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/bucket.py", line 467, in upload_local_file
  File "/usr/local/lib/python3.7/dist-packages/logfury-0.1.2-py3.7.egg/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/bucket.py", line 517, in upload
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/bucket.py", line 601, in _upload_large_file
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/bucket.py", line 601, in <listcomp>
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/utils.py", line 41, in interruptible_get_result
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/bucket.py", line 689, in _upload_part
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/raw_api.py", line 546, in upload_part
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/b2http.py", line 308, in post_content_return_json
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/b2http.py", line 122, in _translate_and_retry
  File "/usr/local/lib/python3.7/dist-packages/b2sdk-1.0.3-py3.7.egg/b2sdk/b2http.py", line 63, in _translate_errors
b2sdk.exception.UnknownError: Unknown error: 400 bad_request more than one upload using auth token 4_0021a87abca5e6b0000000006_01900eb4_738fa9_uplg_Z4DjwblMb-0jss-DQoau3oPpjuE=
```

**Comment by ppolewicz** [comment]
I see. Would you run a version with additional logs and post the logs, so that we can understand how the token reusing happens exactly?

**Comment by ppolewicz** [comment]
@mzukowski-reef found that it's caused by some retryable errors reusing a token (in raw_api retries) while the request is still being processed by the server (if a client-side timeout is shorter than server-side timeout, during processing a request body, for example)
